version: "2"
services:

  tomcat_datavolume:
    container_name: tomcat_datavolume
    image: tomcatdata
    build:
      context: .
      dockerfile: tomcat_war_deploy.Dockerfile

  tomcat:
    container_name: tomcat
    image: tomcat
    build:
      context: .
      dockerfile: tomcat.Dockerfile
    volumes_from:
    - tomcat_datavolume
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports: 
      - 80:80
    links:
      - tomcat:tomcat
    restart: always

